apiVersion: apps/v1
kind: Deployment
metadata:
   name: wso2-apim

spec:
   replicas: 1
   selector:
      matchLabels:
          component: wso2
   template:
      metadata:
          labels:
             component: wso2
      spec:
          containers:
              - name: wso2
                image: wso2/wso2am:3.2.0
                ports:
                    - containerPort: 9443

---
apiVersion: v1
kind: Service
metadata:
    name: wso2-apim-service
spec:
    type: NodePort
    ports:
        - ports: 9443
          targetPort: 9443
          nodePort: 31518
    selector:
        component: wso2
