apiVersion: v1
kind: Service
metadata:
    name: wso2-service
spec:
    type: NodePort
    selector:
        component: wso2
    ports:
       - port: 9443
         targetPort: 9443
         nodePort: 31525
   
